apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pgpupils1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pgpupils1 
    spec:
      containers:
        - name: pgpupils1 
          image: opspgacr.azurecr.io/pgpupils1
          ports:
          - containerPort: 80